vim.pack.add({
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter" },
	{ src = "https://github.com/mason-org/mason.nvim" },
	{ src = "https://github.com/mason-org/mason-lspconfig.nvim" },
	{ src = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim" },
	{ src = "https://github.com/stevearc/oil.nvim" },
	{ src = "https://github.com/nvim-mini/mini.pick" },
	{ src = "https://github.com/nvim-mini/mini.completion" },
	{ src = "https://github.com/neovim/nvim-lspconfig" },
	{ src = "https://github.com/vague2k/vague.nvim" },
	{ src = "https://github.com/christoomey/vim-tmux-navigator" },
	{ src = "https://github.com/stevearc/conform.nvim" },
	{ src = "https://github.com/mbbill/undotree" },
	{
		src = "https://github.com/L3MON4D3/LuaSnip",
		version = "v2.4.1",
		data = { build = "make install_jsregexp", dependencies = "rafamadriz/friendly-snippets" },
	},
	{ src = "https://github.com/rafamadriz/friendly-snippets" },
})
